import re
print(re.match(r'Hey', 'Hey Hey').group(0))
print(re.match(r'Hey', 'hey Hey'))
print(re.search(r'Hey', 'hey Hey').group(0))
print(re.findall(r'Hey', 'hey Hey Hey Hey'))
print(re.split(r'y', 'hey Hey Hey Hey'))
print(re.sub(r'Hey', '?', 'hey Hey Hey Hey'))
ex_str = re.compile('Hey')
result = ex_str.findall('hey Hey Hey')
print(result)
result2 = ex_str.findall('Hey')
print(result2)
print(re.findall(r'h..', 'hey Hey Hey Hey'))
print(re.findall(r'h?', 'hey Hey Hey Hey'))
print(re.findall(r'H.+', 'hey Hey Hey Hey'))
print(re.findall(r'H+', 'hey Hey Hey Hey'))
print(re.findall(r'H*', 'hey Hey Hey Hey'))
print(re.findall(r'\w', 'hey Hey Hey Hey'))
print(re.findall(r'\d', 'hey Hey1 Hey2 Hey3'))
print(re.findall(r'\s', 'hey Hey1 Hey2 Hey3'))
print(re.findall(r'\b\w', 'hey, Hey1, Hey2, Hey3'))
print(re.findall(r'[Hy]', 'hey, Hey1, Hey2, Hey3'))
print(re.findall(r'\.', 'hey. Hey1. Hey2. Hey3'))
print(re.findall(r'..$', 'hey. Hey1. Hey2. Hey3'))
print(re.findall(r'\w{2}', 'hey. Hey1. Hey2. Hey3'))
print(re.findall(r'h|3', 'hey. Hey1. Hey2. Hey3'))
print(re.findall(r'(\w\w\w)', 'hey. Hey1. Hey2. Hey3\n'))
print(re.findall(r'\n', 'hey. Hey1. Hey2. Hey3\n'))